import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/Header/Navbar";
import Footer from "@/components/Footer/Footer";
import { AuthProvider } from "@/context/Auth";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 

  return (
    <html lang="en">
      <body
        className={` ${poppins.variable} antialiased`}
      >
        <AuthProvider>
        <Toaster richColors/>
        <Navbar/>
        <main>{children}</main>
        <Footer/>
        </AuthProvider>
      </body>
    </html>
  );
}
