import type { Booking } from '../types/booking';

export const bookingsData: Booking[] = [
  {
    id: 'BK001',
    apartment: {
      id: 'APT001',
      name: 'Luxury Downtown Loft',
      location: 'Manhattan, NY',
      image: '/placeholder.svg?height=300&width=400',
      rating: 4.8,
      bedrooms: 2,
      bathrooms: 2,
      area: '1,200 sq ft',
    },
    checkIn: 'Mar 15, 2024',
    checkOut: 'Mar 20, 2024',
    guests: 4,
    totalAmount: 1250,
    status: 'accepted',
    bookingDate: 'Feb 28, 2024',
  },
  {
    id: 'BK002',
    apartment: {
      id: 'APT002',
      name: 'Modern Studio Apartment',
      location: 'Brooklyn, NY',
      image: '/placeholder.svg?height=300&width=400',
      rating: 4.5,
      bedrooms: 1,
      bathrooms: 1,
      area: '650 sq ft',
    },
    checkIn: 'Apr 10, 2024',
    checkOut: 'Apr 15, 2024',
    guests: 2,
    totalAmount: 750,
    status: 'pending',
    bookingDate: 'Mar 25, 2024',
  },
  {
    id: 'BK003',
    apartment: {
      id: 'APT003',
      name: 'Cozy Garden Apartment',
      location: 'Queens, NY',
      image: '/placeholder.svg?height=300&width=400',
      rating: 4.2,
      bedrooms: 1,
      bathrooms: 1,
      area: '800 sq ft',
    },
    checkIn: 'May 5, 2024',
    checkOut: 'May 12, 2024',
    guests: 3,
    totalAmount: 980,
    status: 'rejected',
    bookingDate: 'Apr 20, 2024',
  },
  {
    id: 'BK004',
    apartment: {
      id: 'APT004',
      name: 'Penthouse Suite',
      location: 'Upper East Side, NY',
      image: '/placeholder.svg?height=300&width=400',
      rating: 4.9,
      bedrooms: 3,
      bathrooms: 3,
      area: '2,100 sq ft',
    },
    checkIn: 'Jun 1, 2024',
    checkOut: 'Jun 7, 2024',
    guests: 6,
    totalAmount: 2100,
    status: 'accepted',
    bookingDate: 'May 15, 2024',
  },
  {
    id: 'BK005',
    apartment: {
      id: 'APT005',
      name: 'Riverside View Apartment',
      location: 'Long Island City, NY',
      image: '/images/1748107375075-huy-nguyen-AB-q9lwCVv8-unsplash.jpg',
      rating: 4.6,
      bedrooms: 2,
      bathrooms: 2,
      area: '1,100 sq ft',
    },
    checkIn: 'Jul 20, 2024',
    checkOut: 'Jul 25, 2024',
    guests: 4,
    totalAmount: 1150,
    status: 'pending',
    bookingDate: 'Jun 30, 2024',
  },
  {
    id: 'BK006',
    apartment: {
      id: 'APT006',
      name: 'Historic Brownstone',
      location: 'Park Slope, Brooklyn',
      image: '/images/1747867293535-Landlord.jpg',
      rating: 4.7,
      bedrooms: 2,
      bathrooms: 1,
      area: '1,000 sq ft',
    },
    checkIn: 'Aug 12, 2024',
    checkOut: 'Aug 18, 2024',
    guests: 3,
    totalAmount: 1320,
    status: 'accepted',
    bookingDate: 'Jul 28, 2024',
  },
];
